app:
  title: "Asha Grant Analysis 📊       The actual data is broken right now, the UI remains unchanged"
  subtitle: "A data-driven visualization of [Asha Education](https://ashanet.org/) Grant year wise"
  theme: "light"
data:
  source: "data/example_data.csv"
